### ISSUE TITLE
default location for loading ros params

### ISSUE THREAD

**Issue by isucan** [moveit/moveit_ros#180]
When params are not found in ~ (eg, planning, kinematics) try to load the from a default location; eg., /moveit/defaults/planning
/moveit/defaults/kinmatics

**Comment by mikeferguson** [comment]
The description above is a bit different from  the description either #198 or #294. Ideally we would:
- Check <node>/<group>/kinematics
- If not found, check <move_group>/<group>/kinematics
- If still not found, check <move_group>/defaults/kinematics

(I presume here that "moveit" above was meant to be "move_group" -- if not, and we want to put these under moveit, then the setup assistant should probably load these params into "moveit" instead of the local namespace of move_group in the launch files)

**Comment by isucan** [comment]
I actually meant "moveit" to be a namespace for all moveit default parameters. So my thinking is something like
check ~/kinematics; if not found, check /moveit/defaults/kinematics. I would actually change the launch files to load params in the default location, but users then have the option to override the settings by specifying them in the node namespace.

**Comment by isucan** [comment]
i made kinematics be read from robot_description_kinematics if parameters not found under ~
