### ISSUE TITLE
Add support for cartesian trajectories in benchmarks

### ISSUE THREAD

**Issue by marioprats** [moveit/moveit_ros#186]
Should update the benchmark service in order to pass cartesian trajectory constraints down to planners

**Comment by sachinchitta** [comment]
The MotionPlanRequest already has trajectory constraints in it. Is this not sufficient for now - if parsing the whole message to figure out which case to solve for is an issue, we should move the trajectory constraints message out of the motion plan request. Otherwise, we should use the functionality from the current MotionPlanRequest message.

**Comment by isucan** [comment]
I agree with Sachin; @marioprats and I will talk about this; This is covered by #191, so I will close this.
