### ISSUE TITLE
Add ability to load scenes independently of robot details

### ISSUE THREAD

**Issue by chadrockey** [moveit/moveit_ros#20]
It would be nice to be able to load different robots into the same scene.

Currently, if you try to load a different robot or URDF, it makes RVIZ crash complaining that the root link was not found.

There should be a feature to load without robot details, and there should be a check to ensure that if the robot is not compatible with the queries that RVIZ does not crash.

**Comment by isucan** [comment]
fixed. If the robot name does not match, the plugin extracts the geometry only. Tags updated,

**Comment by chadrockey** [comment]
I'm not able to load the geometry:

[ INFO] [1352241657.116251790]: Scene 'ikeaplank' was saved for robot 'robot_arm_description' but we are using robot 'only_arm'. Using scene geometry only
[ERROR] [1352241657.119753404]: Transform from frame 'arm_base_link' to frame 'base_link' is not known ('base_link' should be a link name or an attached body id).

**Comment by isucan** [comment]
Sorry about this -- I was going to send you an email about this but got sidetracked. What happens is that when a scene is actually loaded, it is not set as the planning scene withing the plugin. The reason behind this is because you might want to monitor a planning scene from elsewhere (that's why the planning scene topic is set). The different node that is publishing planning scenes can be sending you diffs, so when loading a scene the scene data is set (in this case the geometry) you might later on (eg, after a few tens of ms) get the diff with the same information, not realizing that diff should be ignored. Essentially the problem comes down to the fact that if you have to have two sources of data for the planning scene to be displayed, synchronization needs to be taken into account and this is difficult to ensure over ROS messages.

Instead, what we are doing is as follows: publish the scene data to a node that listens for it (in this case, move_group). The PlanningScene is sent on the /planning_scene topic and the geometry is sent o the /planning_scene_world topic. Then, that move_group node can publish back to rviz the new data. So instead of synchronizing, we just take a longer trip for the data to get to the plugin.

When you load a planning scene, if your plugin happens to be set to listen on /planning_scene, you get the data for the complete planning scene directly from within the plugin (it publishes to itself). The geometry is not received this way. 

The correct way to do thing is to start dynamic_reconfigure, select /move_group/planning_scene_monitor, turn on the scene publishing, and then in the rviz plugin select as the planning scene topic the topic that move_group publishes. I believe that will be something like /move_group/monitored_planning_scene.
