### ISSUE TITLE
Getting full planning scene from the /move_group/monitored_planning_scene  topic

### ISSUE THREAD

**Issue by taogao** [moveit/moveit_ros#236]
the /monitored_planning_scene only publishes the diffs. It will be great if one can change this behavior and make it publishes the whole planning_scene.

**Comment by isucan** [comment]
That would be too expensive. The topic behaviour should remain as it is, but I will add a move_group capability that publishes planning scenes (service) on request

**Comment by isucan** [comment]
done

**Comment by bit-pirate** [comment]
Could an option to this service be added, which returns the full planning scene? Looks like each available option provides only some parts of it.

**Comment by mikeferguson** [comment]
@bit-pirate what is your actual use case? For instance, one of the things I'd like to see is that the rviz plugin read the full state from the service, and then apply it's updates from the topic that publishes diff (I do something like that so that my objects are always in sync, here: https://github.com/mikeferguson/chessbox/blob/hydro-devel/moveit_utils/src/moveit_utils/object_interface.py) so that you can start/stop the plugin at any time and still have valid scene displayed.

**Comment by mikeferguson** [comment]
Another thought is that the largest part of the planning scene is the octomap -- particularly if you have a massive map in the /odom frame. I'd love to see the equivilant of a "local" map which is restricted to a certain size around the robot's base_link frame (even if only published for visualization). I'm planning to have some free time to work on perception-related aspects in November -- and that particular item is near the top of my list, because I effectively cannot currently use the octomap in the odom frame.

**Comment by mikeferguson** [comment]
@bit-pirate disregard my previous comments, I just reread your comment and saw you were talking about the service...
