### ISSUE TITLE
Moveit Custom IK Plugin

### ISSUE THREAD

**Issue by muhammadaliqasmi** [moveit/moveit_ros#317]
Hi,

I am trying to implement IK with null space optimization plugin for moveit. I followed the step in the following URL 

http://moveit.ros.org/wiki/Kinematics/Custom_Plugin

However, after I make and install catkin package. Everything works fine till here. However, It doesn't list my plugin in the list box of Moveit Setup Assistant. 

I have created the XML file and placed is reference in package.xml.

**Comment by isucan** [comment]
It turns out the instructions in the tutorial you referenced were slightly incorrect. In particular, the <export> bit to be added in package.xml was incorrect. I have fixed that and added a step, with changes needed in your CMakeLists.txt; Let me know if this works. If not, please reopen and attack your package.xml, CMakeLists.txt and new .xml file;
