### ISSUE TITLE
Save desired gripper poses for benchmarking using rviz plugin

### ISSUE THREAD

**Issue by mateiciocarlie** [moveit/moveit_ros#37]
In order to run the benchmark defined in #36, we need to create and save multiple desired gripper poses for each planning scene.
- we would like to save gripper poses from the rviz plugin
- gripper poses should be saved in Cartesian space (position and orientation, arm-independent). 
- we need the ability to name gripper poses, so we can refer to them from the benchmark

helping: @isucan @marioprats

**Comment by isucan** [comment]
The gripper poses should be saved using the ConstraintsStorage class in moveit_ros_warehose. A pose is just a PositionConstraint and an OrientationConstraint. We probably need an additional Tab in the Rviz plugin to allow operating with these goal poses. I'd like this tab to include operations with RobotState messages as well -- saving them using the RobotStateStorage class in moveit_ros_warehouse. This will allow us to specify initial states for the benchmarking step as well.

**Comment by marioprats** [comment]
I'm thinking on a new tab where the user can create goal groups (or 'problems'), and set target poses for those groups. A group could have one or several target poses. I will have a look to the constraint classes you mention for the implementation. Do we need to set the initial robot state with the rviz plugin as well? this would require opening each scene for a given robot, and then setting the initial pose, right? that could be a long task, and we probably want the same starting configuration for all the scenes. How about setting the initial pose as a parameter to the benchmark given on the command line, or read from a configuration file?

**Comment by isucan** [comment]
I don't think we should add benchmarking capabilities to this rviz plugin. Perhaps we will develop a different GUI / plugin, but for this one I was thinking we just use it to populate the database.
The way I have set up the benchmarking command line tools is that you define cfg files for the problem:

[scene]
name=some_name  (can be saved from rviz)
query=some_regex (selection of queries specified in rviz; can be empty)
goal=some_regex (selection of constrains; to be specified in rviz; can be empty)

So the groups you talk about are defined by the regular expressions. It could be that for some problems, poses are shared so I do not think we should save the notion of groups of poses in the db itself. Furthermore, we could use more general representations of problems (different Constraints), not just sets of eef poses.

About start states, the plan is to do things exactly as you suggest. There is another regex defining start states to use in the [scene] section of the .cfg file. But we still need to save those states under specific names. So I was thinking to have an option to save the start/goal states in the rviz plugin under some name. This would be something like a Save As button, a QInputDialog pops up to specify the name of the state, it gets saved. A QList of named states should be in a tab of the plugin frame as well, so we can rename & remove states as well.
Do you think this is ok to do?

(Btw, use qt designer to edit the ui)

**Comment by mateiciocarlie** [comment]
So the rviz plugin is essentially an interface for storing things to the database, and knows nothing about benchmarking? The cfg file then uses regex to tell the benchmark what to run on. 

In general, I think the suggested architecture makes a lot of sense and looks fine to me.

**Comment by isucan** [comment]
@mateiciocarlie Yes, that is what I was thinking.

**Comment by marioprats** [comment]
Good, makes sense. Do we want to set start states moving joint by joint, or just IK-based as it is now? I would start using IK for now, but we may need to have control of the joints in the future (e.g if the start state is a folded configuration for which the joint angles are known). That might be another ticket though...

**Comment by isucan** [comment]
I think IK is fine for now

**Comment by mateiciocarlie** [comment]
Note that goal poses have to be robot-independent, so defining them by moving a particular robot around, and only in places that it can reach, is intrinsically flawed. We do need an easy way to define goal poses though...

**Comment by marioprats** [comment]
I have submited a pull request (#49) with the basic functionality. Let's start improving from here. 
There is a new tab that allows to:
- Create goals in the cartesian space. When creating a new goal, it appears by default at the current end effector pose of the goal kinematic state. Once created it is an interactive marker that can be dragged around. The marker is an arrow for now, although in the future could be nice to show a robot hand urdf as suggested by @adamantivm 
- Select and move multiple goals. By clicking on the marker you can select/unselect it. The same by clicking on the name in the list. When selected the controls are shown so that you can interact. If multiple markers are selected, all of them will move when dragging one. My idea was to combine this with the capability of duplicating markers (Ctrl-C for instance, still to do!). This would allow easy and quick creation of goal poses (imagine you have a set of poses on top of a shelve, and want to create the same for a contiguous one).
- Storing/loading goals into/from the database as Constraint messages. It is not clear for me how we will relate these goals to a planning scene. Currently they are independent, but for our benchmarks we'll need to associate them. A set of goal poses will only make sense for a specific planning scene geometry, and in the rviz plugin we want to load only the goals defined for a scene, and not all. The easiest solution I guess would be to prepend the scene name to the goal names, and them filter them according to this, but ideally it would be great to link them explicitly (a planning_scene field in the Constraint msg?). Any ideas?

Still to do:
- Store start states. The storage object is already there, just have to create the gui elements and logic.
- Rename goals, individually and for a selected group.
- Your suggestions ;)

**Comment by isucan** [comment]
Mario, thanks for the pull request. It is now merged. 
I put some comments on the code you wrote (I just discovered the feature). Perhaps those can be addressed in a later request, although at this point I think point you should switch to developing on groovy-devel as your feature updates are mostly there.

About the question above on the relation of planning scenes and constraints. The association does not need to be explicit in the database. The plan is to associate these when you write a .cfg file for the benchmark to run. I don't think the naming you suggest should not be part of the rviz plugin. We should not force the users how to name their goals. Perhaps the scene name as a prefix would be a good default for your getText() call, but the user of course has the option to delete that.

**Comment by mateiciocarlie** [comment]
I was just able to try it out on my machine. Good stuff!

A few comments:
- yes, having the IM show up using the currently loaded hand urdf would be great :)
- (minor) when multiple poses are selected, they all move in their own reference frame. I think it might be more intuitive if they all moved the same way in the frame of the one that the user is actually dragging around
- the big one: associations. I totally agree with @isucan that the most general way is to not have associations forced on the user by making them explicit in the database. However, we do need a way to make the associations as a convenience tool. Poses will mostly make sense for a single (or a few) scene(s); I expect we'll end up with 10+ scenes and 1000+ goal poses. We will need a way to say "only load and show me the poses that somebody has decided make sense for this scene". Even for the benchmark .cfg file we'll need a convenient way to specify which poses we want with which scene in the benchmark; listing 100 4-digit numbers as pose ID's is going to be difficult and error-prone...

**Comment by isucan** [comment]
@mateiciocarlie The benchmarking supports regex to specify goals, so perhaps if the user follows a convention for specifying goals (such as scenes_and_b_goal_XXX where XXX are numbers) then this becomes easier. Mario and I just spoke about adding the same regex filtering functionality to the rviz plugin  as well.

**Comment by mateiciocarlie** [comment]
Got it - sounds like a good plan to me.

Although it is true that in most cases poses will only make sense in certain scenes. I feel that when such constraints exist, I would rather see them enforced at a lower level (e.g. database) then rely on user conventions. However, I don't think this issue is worth too much debate and I don't want it to get philosophical. If you guys are happier with naming conventions then that is OK by me.

**Comment by marioprats** [comment]
Hi, thanks for the comments
I've submitted another iteration. It should fix the way multiple goals are moved (now relative to the one being dragged), and also adds the functionality for storing start states. I have added the regex text field for filtering the input, and default names when storing goals and states. That will allow to filter the database data for the current scene. Let's see if this is usable or we need to make a more explicit relationship in a database... Also fixes some coding style (thx for the rules @isucan! let me know any others!)

Still need to rethink a bit the UI, but the basic functionality should already there. Will try and end-to-end run tomorrow (#38).

**Comment by isucan** [comment]
@marioprats I played with this a little bit and it seems to work well. Thanks for the updates. One weird thing: If I connect to the db, load, everything is fine. Then I disconnect, but all UI elements in the new tab remain populated. I think we should trigger a clear when the tab is changed, and if the db connection is there, automatically load the db?

**Comment by marioprats** [comment]
Not sure if that's what we want. The user may have goals created from the GUI and not stored in the DB. If we clear everything when switching to another tab, those would be lost. The way it is now is like an 'Import from DB'. Once the goals are imported they are stored locally and the user can play with them even without a DB. Actually it would be possible to load goals from a DB, switch to another DB and store them in the new. We should probably call the button 'Import...' and then show a dialog for the regex. I don't like the regex appear on top of the list, it seems like a filter on the list rather than a filter at the moment of loading.

The last pull request adds the possibility to duplicate goal poses (pressing ctrl-c on a selection). The naming is an issue, but as long as the default names are used it should be fine ;) Also, by double clicking on a goal pose, IK is computed for that pose. 

If you are fine I would close this issue and then open new tickets for bugs/enhancements.

**Comment by adamantivm** [comment]
One small comment from the user point of view: it is confusing that the
funtionality of this new tab is inconsistent with the functionality of the
planning scenes tab. On the latter, after you connected to the database,
you have all the scenes already loaded. In this new one, you have to click
a specific "Load" button. I don't have a strong opinion one way or another,
but I would strongly suggest being consistent throughout the UI.

**Comment by marioprats** [comment]
We can load by default all the goals matching scenename.\* when loading a scene. This would populate the goal list as long as the goals were created using the default suggested names. But we'll still need the load button in case the user wants to load other goals.

**Comment by isucan** [comment]
@marioprats I think we should always load all the goals when loading from the database and use the regex as a filter. When the user changes the regex, a different set of goals are shown. Then the user can copy a goal originally developed for one scene to another scene. It also allows the user to check whether the regex is correct. Otherwise, if you have a regex used at load time, you filter data you do not yet see. I think this is very confusing.
With respect to the rename, I would rather do what is done for copying collision objects. When you click Ctrl +C, you do not really have to offer the user the option to rename, as long as that is available later. You just need a unique name. If you do have the user fill in a name, you have to double check that name is unique. If it is not, fail.

**Comment by adamantivm** [comment]
I agree with @isucan about loading all goals but showing a subset depending
on a regex. The regex can in turn (and should by default) change when the
user changes the scene. An option to disable the filter or allow changing
it manually would allow access to goals from other scenes.
- Julian

**Comment by marioprats** [comment]
Ok, then let's load everything when connecting to a db, and apply the regex scene.\* by default filter when loading a scene. The regex field will always be there in case the user wants to change the filter.
Regarding renaming, let's say I have a scene with shelves. I have defined 50 goals on top of one shelve, and want to copy all of them to the shelve above. I do not want to rename one by one ;) So, the current approach is to asign a unique name following the convention scene_goal_number. But I agree a renaming functionality will not hurt anyone.

btw, should we open a ticket for agreeing on UI conventions and fixing inconsistencies?

**Comment by marioprats** [comment]
The basic functionality is there, so let's now open more concrete tickets

**Comment by mateiciocarlie** [comment]
Excellent work. Playing around with the goals is a lot of fun. I think this is indeed pretty much solved.

One note: the regex does not work for me, for the start state or the goals. Does it work for you with the latest version of everything?

**Comment by marioprats** [comment]
It works for me, but the UI is still a bit tricky, and there are a few things you need to know:
- The filter field does not work as a filter on the current list. It's the filter applied when getting things from the DB when you click Load. So, if you change the regex, you want to reload from the DB.
- The Load button works as an import. Everything you load is aggregated to what you already have in the list.

So the process is Load->Filter->AddToList. To avoid confusion, what about clearing the list when pressing Load, and automatically load when changing the regex?

**Comment by mateiciocarlie** [comment]
Oh, I see. 

Yes, the current UI is a bit confusing.

I don't think there is an ideal solution. Our main use case will be creating lots of goal poses for benchmarking. Let's wait until we have the planning scenes defined and start doing that in earnest, and then we can solve the interaction issues that are driving us crazy as we're doing that.

**Comment by adamantivm** [comment]
I concur

**Comment by isucan** [comment]
You can even keep everything internally after a load and when the regex changes, you just copy from the internal list to the QWidget the items that match the regex. It would be significantly more efficient for fast editing of the regex, especially if the db is remote.

**Comment by mateiciocarlie** [comment]
Would also be nice if we had a way to check if a disembodied gripper placed at the goal pose is in collision with something (see #71).

How doable is this?

**Comment by isucan** [comment]
@mateiciocarlie this is already done. The KinematicState allows doing FK for particular parts of the robot only (the updateStateWithLinkAt() function) so we can place parts of the robot anywhere we want (even though this 'breaks' the robot) and the collision checking  we use allows specification of a group (optional) to limit the collision checking to.

**Comment by marioprats** [comment]
I'll close this one and open another more specific for Matei's request (#82)
