### ISSUE TITLE
Move Group Interface asserts on shutdown

### ISSUE THREAD

**Issue by acornacorn** [moveit/moveit_ros#392]
To repro run the tutorial

roslaunch pr2_moveit_tutorials move_group_interface_tutorial.launch

or 

roslaunch pr2_moveit_tutorials move_group_python_interface_tutorial.launch

and see

boost::pthread::pthread_mutex_scoped_lock::pthread_mutex_scoped_lock(pthread_mutex_t*): Assertion `!pthread_mutex_lock(m)' failed

**Comment by cmaestre** [comment]
This problem is still in the latest versions of ROS Hydro + MoveIt!, even when making the simplest planning example:

```
#include <moveit/move_group_interface/move_group.h>
int main(int argc, char **argv)
{
  ros::init(argc, argv, "movement_example1");
  ros::NodeHandle node_handle;  
  ros::AsyncSpinner spinner(1);
  spinner.start();

  // Part of the robot to move
  moveit::planning_interface::MoveGroup group("right_arm");

  // specify that our target will be a random one
  group.setRandomTarget();

  int res = group.move();  
  ros::shutdown(); 
  return 0;
}
```

Finding that problem at the end of the running of the example makes not possible to use Valgrind with it. And therefore it is not possible to detect memory leaks, an important issue when launching long experiments (several days), because the memory gets full and ROS crashes.

**Comment by v4hn** [comment]
The problem is not reproducible in current `indigo-devel` anymore.
If you still experience this bug, feel free to open a new request with a concrete test case.
