### ISSUE TITLE
PlanningSceneDisplay does not render OctoMap

### ISSUE THREAD

**Issue by isucan** [moveit/moveit_ros#45]
The PlanningSceneDisplay has support for rendering simple shapes and meshes. However, rendering octomaps is not supported. We should use the existing octomap rviz plugin to render the octomap part of a plannig scene as well.
Anyone up for this?

People who can probably help:
@marioprats @jkammerl @dgossow @isucan @aleeper

**Comment by jkammerl** [comment]
Yes, I recently worked on two rviz plugins for displaying binary octomap messages in rviz:
https://github.com/ros-visualization/octomap_rviz_plugins
One displays a 3d voxel grid and the other generates a 2d map. 
Do they work for you? Since I am still new to moveit, it would be great if you could give me some pointers how to integrate them best.

**Comment by isucan** [comment]
Julius, I think we would like to use the grid display. I just looked at your code. I think integration should work fine.

This is the rendering code we have for planning scenes:
https://github.com/ros-planning/moveit-ros/blob/groovy-devel/visualization/planning_scene_rviz_plugin/src/planning_scene_render.cpp

It basically renders shapes. One particular type of shape is a wrapper for an octree (see https://github.com/ros-planning/geometric_shapes/blob/master/include/geometric_shapes/shapes.h)

So what I think we need to do is to create an instance of the rviz plugin for octomaps within the PlanningSceneDisplay and pass the octree from the shape to that plugin. If the rendering functionality from the octomap plugin can be made accessible as a lib, I think integration would be even easier. Does this sound right? We can talk about this in more detail if you like.

**Comment by jkammerl** [comment]
Thanks Ioan, yesterday I talked to Sachin about it. He will give me some more instructions on how to integrate it best, since I have not had the change to work with this part of the move-it code. I would like to reinstall/update moveit now. Do these instructions still work (with respect to recent changes?) Which branches should I use.

**Comment by jkammerl** [comment]
http://moveit.ros.org/installation_source.html

**Comment by jkammerl** [comment]
Hi, what's the easiest way to get an octree shape within move-it? would it be possible to add an octomap to the warehouse at rlu.willowgarage.com? This way, I could test the rendering of an octree within the planning_scene_rviz_plugin. Thanks!

**Comment by isucan** [comment]
The easiest way is to publish a PlanningScene message on the topic that the rviz plugin listens to.
So that you do not have to fill anything but the octomap, just set
msg.is_diff = true;
msg.world.octomap = .... ; this is an OctomapWithPose msg;

**Comment by jkammerl** [comment]
Hi, I just added the octomap visualizer to the render_shapes class and triggered a pull-request. I tested it with randomly generated octree data and it looks fine. However, if we would like to update the octree structures at high rate, we should perform the octree decoding and the rviz point cloud generation outside of the visualization thread. What do you think?

**Comment by isucan** [comment]
Thanks for the pull request @jkammerl !
It is now merged. I think we should do the decoding in a background thread, but let's first see how bad things get.

I have a question about the code: what are the 16 levels you construct point clouds for?
Do we really need the dependency on octomap_ros? I removed a number of unneeded #includes and I do not see octomap_ros headers included.

**Comment by jkammerl** [comment]
Rviz can render a set of boxes very efficiently on the GPU by using a pointcloud with point type "boxes." This way you only need to transmit point data to the GPU instead of meshes. However, to every pointcloud, you can  assign only a single point/box size that is applied to every point in the cloud. Therefore I added a pointcloud for each level of the octree. Since octomap uses 16-bit shorts as voxel keys, this leads to 16 separate pointclouds to render all possible voxels in the octree. 

Thanks for cleaning up the code. And yes, octomap_ros is not needed anymore.

**Comment by isucan** [comment]
Thanks for the clarification! Is there a way to get the value 16 as a constant from octomap?

**Comment by jkammerl** [comment]
I didn't find a constant within the octomap code defining the key size. We could use sizeof(unsigned short int)*8

**Comment by isucan** [comment]
That's fine. Maybe @ahornung will add a named constant  in octomap and we will be able to use that. Or we can use 8 \* sizeof (some octomap typedef) , which currently is defined to be unsigned short it.

**Comment by ahornung** [comment]
Just use octree.getTreeDepth()

That defines the depth levels, currently a constant but it can be overriden by a custom implementation (and already was - there is some modified version with 32 levels around).

**Comment by ahornung** [comment]
In terms of speeding up things, you could include a parameter "max depth" that is changeable on the fly like in octovis or octomap_server via dynamic_reconfigure. Pass that to the iterators and you will get an immediate speedup. Just iterating over the tree will already be twice as fast for one less depth level, I assume rendering will benefit even more (= less voxels).

This greatly helped us visualizing whole rooms while navigating, and still using a fine resolution for collision checks.

**Comment by jkammerl** [comment]
Thanks @ahornung! Very helpful! I added an optional parameter to the OcTreeRender class which allows to limit the tree depth. I also integrated the getTreeDepth method to obtain the amount of tree levels.
