### ISSUE TITLE
moveit_ros_planning failing to build on indigo

### ISSUE THREAD

**Issue by tfoote** [moveit/moveit_ros#519]
http://jenkins.ros.org/view/IbinS32/job/ros-indigo-moveit-ros-planning_binarydeb_saucy_i386/69/console

It looks like a missing dependency declaration. 

```
-- Using these message generators: gencpp;genlisp;genpy
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for module 'eigen3'
--   found eigen3, version 3.2.0
-- Found Eigen: /usr/include/eigen3  
-- Eigen found (include: /usr/include/eigen3)
CMake Error at /usr/share/cmake-2.8/Modules/FindQt4.cmake:1382 (message):
  Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x
Call Stack (most recent call first):
  CMakeLists.txt:25 (find_package)


-- Configuring incomplete, errors occurred!
dh_auto_configure: cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCATKIN_BUILD_BINARY_PACKAGE=1 -DCMAKE_INSTALL_PREFIX=/opt/ros/indigo -DCMAKE_PREFIX_PATH=/opt/ros/indigo returned exit code 1
make[1]: *** [override_dh_auto_configure] Error 2
```

**Comment by mikeferguson** [comment]
I think this is caused by removing PCL (apparently, this is the first 0.6.0 release). Looks like we used to get qt via pcl-all -> vtk -> qt.

This does raise another issue, is that we should get devel jobs running for Indigo on the farm (previously we were using travis, but since it doesn't support indigo, we should get the farm jobs running to catch things like this). I created a separate issue to track that https://github.com/ros-planning/moveit_ros/issues/520
