### ISSUE TITLE
Goal poses shift

### ISSUE THREAD

**Issue by marioprats** [moveit/moveit_ros#92]
For some reason goal poses created at some point may shift a bit from its original position. I've not been able to reproduce this effect, but it has been reported by @mateiciocarlie and I also noticed that in previously created scenes. If someone has the honor to see it happen, any info will be appreciated ;)

**Comment by isucan** [comment]
i suspect this is not a frame change in the rviz fixed frame?

**Comment by marioprats** [comment]
Actually they appear already shifted in the wiki snapshots, so probably they were like that since the beginning. @adamantivm ?

**Comment by adamantivm** [comment]
I will double-check tomorrow (I don't have access to the computer with rviz
at home).

Is it possible that this is a confusion on the representation of the goal
pose? I don't see the shifted position in the screenshots. All the bottom
shelf grasp points are designed to position the gripper barely inside the
bin. Note that the gripper is placed at the tip of the blue arrow. The
overhead poses should then be the ones with the blue arrow pointing down,
which aren't visible in the lower shelf in the screenshot:
https://f.cloud.github.com/assets/2230382/11901/a6b1d722-456b-11e2-8382-7279ac934517.png

Again, I will check this tomorrow in rviz and it is indeed possible that I
may have misplaced the goals (it is hard to see exactly where you're
positioning them when you move a group because it becomes full of pretty
big interactive markers which occlude the view of the disembodied gripper).

If you can identify a particular goal pose which falls outside the bin,
please share the goal pose name with me so that I can debug more easily.

**Comment by marioprats** [comment]
You are right @adamantivm. Having a closer look the ones that seem outside are actually forward grasps, and the gripper falls on top of the support. So everything seems fine. But open it again if you finally discover an issue
